= Anypoint Exchange
:keywords: exchange, exchange2, anypoint exchange

Anypoint Exchange provides a unified user interface and API for discovery and consumption of connectivity and API assets.

== Why Use Exchange?

You can use Exchange to:

* *Increase productivity and accelerate onramp* for new users by building categories filled with crucial information. For example, MuleSoft published a category called “Getting Started”, which provide users with essential assets to become acquainted with Anypoint Platform.

* *Ensure there is alignment and adoption* on how to accomplish tasks in the manner compliant with your organization’s standards, policies, or guidelines, such as error handling, auditing, authentication, etc.

* *Share and build on best practices*. Users can adopt best practices by searching or browsing Exchange, and suggest enhancements as they improve their understanding of existing assets.

== Types of Assets

Exchange provides assets for:

* *Connectors* - Packaged connectivity to an endpoint developed and deployed on MuleSoft’s Anypoint Platform with third-party APIs and standard integration protocols. Anypoint Studio is preloaded with a large set of connectors, but the full listing can be found on the Exchange. View details on applications that provide connections between resources. To install connectors, open Exchange from within link:https://www.mulesoft.com/platform/studio[Anypoint Studio].

* *Templates* - Packaged integration patterns that address common use cases and are built on best practices. Use case applications to which you add your information to complete a user case or solution.

* *Examples* - Implementation projects that explain development elements within Anypoint Studio and how these can be leveraged to achieve specific API and integration objectives. Examples are applications that are ready to run and demonstrate a use case or solution.

* *REST APIs* - API descriptions. See raml.org for more information.

* *SOAP APIs* - API descriptions in a WSDL that helps make the adoption of the Anypoint Platform easier and faster.

* *Others* - Blogs/Articles/Videos and more - Links that assist with knowledge sharing, such as information on DataWeave, MEL, batch processing, MUnit, policies, and links to knowledge sharing information sources.

Exchange provides the ability to discover public assets provided by MuleSoft in addition to the catalog and discovery of private assets. All public content is provided and certified by MuleSoft, and partner connectors have been reviewed and approved by MuleSoft. All private content is internal to an organization and not exposed externally. Customers are responsible for any private content published within their Exchange.

== Navigating Anypoint Exchange

You can search Anypoint Exchange using tags and keywords for a name, summary, description, and tags of the items. Each element is tagged with labels that refer to a version, the Mule Runtime versions it supports, etc. These are also organized by pattern so you can scan through only those that perform what you’re interested in.


== See Also

* link:/anypoint-exchange/access[Access Exchange]
* link:/anypoint-exchange/consume[Consume from Exchange]
* link:/anypoint-exchange/install-connector[Install a Connector]
* link:/anypoint-exchange/create-portal[Create Portal]
* link:/anypoint-exchange/add-asset[Add Asset]